import 'dart:convert';
import 'dart:io';

import 'package:ffmpeg_kit_flutter_new/ffmpeg_kit.dart';
import 'package:ffmpeg_kit_flutter_new/return_code.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;
import 'package:integration_test/integration_test.dart';
import 'package:onekit_converter/engine/converters/converter.dart';
import 'package:onekit_converter/engine/engine.dart';
import 'package:onekit_converter/engine/format.dart';
import 'package:onekit_converter/engine/job.dart';
import 'package:onekit_converter/engine/registry.dart';
import 'package:path/path.dart' as p;

/// Runs the real engine on a real device against every format OneKit claims.
///
/// The pure-Dart converters are covered by `test/converters_test.dart`, which
/// runs on the host. This suite exists for what that cannot reach: FFmpeg and
/// pdfium, which need the platform's native libraries.
///
/// Rather than attempt all 6,126 pairs (which would take hours of device time
/// for no extra signal), it walks the matrix by capability: every *decodable*
/// format is converted to a canonical target, and every *encodable* format is
/// produced from a canonical source. Between them, every codec path the app can
/// take is executed at least once.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  late Directory work;
  final failures = <String, String>{};
  final passes = <String>[];

  setUpAll(() async {
    work = await Directory(p.join((await ConversionEngine.tempDir()).path, 'matrix'))
        .create(recursive: true);
  });

  tearDownAll(() {
    // One consolidated report; per-test output would be unreadable at this size.
    final total = passes.length + failures.length;
    debugPrintMatrixReport(total: total, passes: passes, failures: failures);
    work.deleteSync(recursive: true);
  });

  FileFormat fmt(String ext) => FormatRegistry.byExt(ext)!;

  /// Converts [source] to [toExt] and records the result. Returns the output
  /// path, or null if the conversion failed.
  Future<String?> convert(String label, String source, String toExt) async {
    final job = ConversionJob(
      id: label,
      sourcePath: source,
      target: fmt(toExt),
      options: const ConvertOptions(quality: 80, pdfDpi: 72),
    );
    await ConversionEngine.instance.run(
      job,
      cancel: CancelToken(),
      outputDirectory: work.path,
    );

    if (job.status == JobStatus.done && job.outputBytes > 0) {
      passes.add(label);
      return job.outputPath;
    }
    failures[label] = job.error ?? 'status=${job.status.name}';
    return null;
  }

  // ------------------------------------------------------------- fixtures

  /// Canonical sources, one per family, built on device so the test has no
  /// binary assets to keep in sync.
  late String pngSeed;
  late String wavSeed;
  late String mp4Seed;
  late String pdfSeed;

  test('build fixtures', () async {
    // A PNG from the pure-Dart encoder is the root of the image tree.
    final png = File(p.join(work.path, 'seed.png'));
    await png.writeAsBytes(_seedPng());
    pngSeed = png.path;
    expect(await png.length(), greaterThan(0));

    // A tone encoded as WAV seeds the audio tree, generated by FFmpeg's lavfi
    // source so the test carries no binary fixtures.
    final wav = File(p.join(work.path, 'seed.wav'));
    await _ffmpegGenerate(
      ['-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', '-ac', '2', wav.path],
    );
    expect(await wav.exists(), isTrue, reason: 'could not generate the audio fixture');
    wavSeed = wav.path;

    final mp4 = File(p.join(work.path, 'seed.mp4'));
    await _ffmpegGenerate([
      '-f', 'lavfi', '-i', 'testsrc=size=320x240:rate=15:duration=2',
      '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2',
      '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest',
      mp4.path,
    ]);
    expect(await mp4.exists(), isTrue, reason: 'could not generate the video fixture');
    mp4Seed = mp4.path;

    // A PDF built by the app's own document path seeds the PDF tree.
    final md = File(p.join(work.path, 'seed.md'))
      ..writeAsStringSync('# Seed\n\nA paragraph of text for extraction.\n\n- one\n- two\n');
    pdfSeed = (await convert('seed:pdf', md.path, 'pdf'))!;
  });

  // ---------------------------------------------------------------- images

  test('every image format decodes', () async {
    // Reach each decodable format by first encoding into it, then reading it
    // back out to PNG. A format that cannot be produced is skipped rather than
    // reported as a decode failure.
    for (final f in FormatRegistry.family(Family.image)) {
      if (!f.read) continue;
      final encoded = f.write ? await convert('png>${f.ext}', pngSeed, f.ext) : null;
      if (encoded == null) continue;
      await convert('${f.ext}>png', encoded, 'png');
    }
  }, timeout: const Timeout(Duration(minutes: 20)));

  test('every image format encodes from PNG', () async {
    for (final f in FormatRegistry.family(Family.image)) {
      if (!f.write || f.ext == 'png') continue;
      await convert('img:png>${f.ext}', pngSeed, f.ext);
    }
  }, timeout: const Timeout(Duration(minutes: 20)));

  // ----------------------------------------------------------------- audio

  test('every audio format encodes and decodes', () async {
    for (final f in FormatRegistry.family(Family.audio)) {
      if (!f.write) continue;
      final encoded = await convert('aud:wav>${f.ext}', wavSeed, f.ext);
      if (encoded == null || !f.read) continue;
      await convert('aud:${f.ext}>wav', encoded, 'wav');
    }
  }, timeout: const Timeout(Duration(minutes: 30)));

  // ----------------------------------------------------------------- video

  test('every video format encodes and decodes', () async {
    for (final f in FormatRegistry.family(Family.video)) {
      if (!f.write) continue;
      final encoded = await convert('vid:mp4>${f.ext}', mp4Seed, f.ext);
      if (encoded == null || !f.read) continue;
      await convert('vid:${f.ext}>mp4', encoded, 'mp4');
    }
  }, timeout: const Timeout(Duration(minutes: 40)));

  test('video crosses into audio and image', () async {
    await convert('cross:mp4>mp3', mp4Seed, 'mp3');
    await convert('cross:mp4>wav', mp4Seed, 'wav');
    await convert('cross:mp4>gif', mp4Seed, 'gif');
    await convert('cross:mp4>png', mp4Seed, 'png');
    await convert('cross:png>mp4', pngSeed, 'mp4');
  }, timeout: const Timeout(Duration(minutes: 10)));

  // ------------------------------------------------------------------- pdf

  test('PDF renders to images and extracts text', () async {
    for (final ext in ['png', 'jpg', 'bmp', 'tiff', 'webp']) {
      await convert('pdf>$ext', pdfSeed, ext);
    }
    for (final ext in ['txt', 'md', 'html', 'json', 'csv', 'epub']) {
      await convert('pdf>$ext', pdfSeed, ext);
    }
  }, timeout: const Timeout(Duration(minutes: 10)));

  test('images become PDF pages', () async {
    for (final ext in ['png', 'jpg', 'webp', 'bmp']) {
      final img = ext == 'png' ? pngSeed : await convert('mk:$ext', pngSeed, ext);
      if (img == null) continue;
      await convert('$ext>pdf', img, 'pdf');
    }
  }, timeout: const Timeout(Duration(minutes: 10)));

  // --------------------------------------------------------------- summary

  test('the whole matrix succeeded', () {
    expect(
      failures,
      isEmpty,
      reason: 'failed conversions:\n${failures.entries.map((e) => '  ${e.key}: ${e.value}').join('\n')}',
    );
  });
}

void debugPrintMatrixReport({
  required int total,
  required List<String> passes,
  required Map<String, String> failures,
}) {
  // ignore: avoid_print
  print('\n=== OneKit format matrix ===');
  // ignore: avoid_print
  print('ran $total conversions: ${passes.length} passed, ${failures.length} failed');
  for (final e in failures.entries) {
    // ignore: avoid_print
    print('  FAIL ${e.key}: ${e.value}');
  }
}

/// Generates a fixture with FFmpeg directly. The engine converts between files;
/// here there is no input file yet, so FFmpeg is driven straight.
Future<void> _ffmpegGenerate(List<String> args) async {
  final session = await FFmpegKit.executeWithArguments(['-hide_banner', '-y', ...args]);
  final code = await session.getReturnCode();
  if (!ReturnCode.isSuccess(code)) {
    final logs = await session.getAllLogsAsString() ?? '';
    // Only the tail matters; a full FFmpeg log would bury the failure.
    final tail = const LineSplitter().convert(logs).reversed.take(6).toList().reversed;
    fail('fixture generation failed:\n${tail.join('\n')}');
  }
}

/// A 64x48 gradient with a hard edge down the middle, so lossy encoders have
/// both smooth and sharp content to work on.
List<int> _seedPng() {
  final image = img.Image(width: 64, height: 48);
  for (var y = 0; y < 48; y++) {
    for (var x = 0; x < 64; x++) {
      image.setPixelRgb(x, y, x * 4 % 256, y * 5 % 256, (x < 32) ? 20 : 230);
    }
  }
  return img.encodePng(image);
}
